### ISSUE TITLE
rancid avaya switch ERS

### ISSUE THREAD

**Issue by rancid78** [ajschroeder/rancid#1]
Hello 
how can i integrated nortellogin and nortelrancid  with ./cloginrc and router.db
is there un tutorial that explan how to modifiy rancid/bin files

**Comment by ajschroeder** [comment]
Not a tutorial really, but how you integrate my changes depends largely on the version of RANCID you are running. I am running 2.x and not the newer 3.x.

To make the changes in 2.x you need to modify the rancid-fe file and add the name and the rancid script to run in the vendortable array, for example:

%vendortable = (
     ...
     'nortel'    => 'nortelrancid',
     'passport'     => 'passrancid',
     ...
);
